apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ssti-demo-app
  name: ssti-demo-app
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssti-demo-app
  template:
    metadata:
      labels:
        app: ssti-demo-app
    spec:
      containers:
      - image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-076-24_kimai-cve-2023-46245:web
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        name: web
        ports:
        - containerPort: 5000
          name: http
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ssti-demo-app
  name: ssti-demo-app-service
  namespace: sandbox-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: ssti-demo-app
  type: ClusterIP
