apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: geonode-wps
  name: geonode-wps-deployment
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: geonode-wps
  template:
    metadata:
      labels:
        app: geonode-wps
    spec:
      containers:
      - image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-096-24_pywps-cve-2021-39371:geonode-wps
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /ping
            port: 5000
          failureThreshold: 10
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        name: geonode-wps
        ports:
        - containerPort: 5000
          name: http
        readinessProbe:
          httpGet:
            path: /ping
            port: 5000
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: geonode-wps
  name: geonode-wps-service
  namespace: sandbox-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: geonode-wps
  type: ClusterIP
