apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fontforgepro
  name: fontforgepro-deployment
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fontforgepro
  template:
    metadata:
      labels:
        app: fontforgepro
    spec:
      containers:
      - env:
        - name: FLAG
          value: FLAG_PLACEHOLDER
        image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-096-24_fonttools-cve-2023-45139:fontforgepro
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - python3
            - -c
            - import urllib.request; 
              urllib.request.urlopen('http://localhost:5000/')
          failureThreshold: 10
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        name: fontforgepro
        ports:
        - containerPort: 5000
          name: http
        readinessProbe:
          exec:
            command:
            - python3
            - -c
            - import urllib.request; 
              urllib.request.urlopen('http://localhost:5000/')
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fontforgepro
  name: fontforgepro-service
  namespace: sandbox-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: fontforgepro
  type: ClusterIP
