apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pywps
  name: pywps-deployment
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pywps
  template:
    metadata:
      labels:
        app: pywps
    spec:
      containers:
      - env:
        - name: FLAG
          value: FLAG_PLACEHOLDER
        image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-096-24_pywps-cve-2021-39371:pywps
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          failureThreshold: 10
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        name: pywps
        ports:
        - containerPort: 5000
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pywps
  name: pywps-service
  namespace: sandbox-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: pywps
  type: ClusterIP
