services:
  web:
    build: 
      context: ./src
      args:
        - FLAG
    ports:
      - "8080:80"
    healthcheck:
      test: curl -f http://localhost:80/health || exit 1
      timeout: 5s
      retries: 10
      interval: 10s
      start_period: 10s
