services:
  db:
    build: ./mysql
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=netwatch_monitoring", "-u", "root"]
      timeout: 1s
      retries: 5
      interval: 10s

  netwatch_nms:
    build:
      context: ./app
      args:
        - FLAG
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=netwatch_monitoring
      - DB_NAME=netwatch
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/ping"]
      timeout: 1s
      retries: 5
      interval: 10s
