apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: idor-broken-authz-trading-platform
  name: idor-broken-authz-trading-platform
  namespace: sandbox-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idor-broken-authz-trading-platform
  template:
    metadata:
      labels:
        app: idor-broken-authz-trading-platform
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: idor_broken_authz_trading_platform
        - name: MYSQL_DATABASE
          value: database
        image: /:-mysql
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - --password=idor_broken_authz_trading_platform
            - -u
            - root
          failureThreshold: 5
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: db
        ports:
        - containerPort: 3306
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - --password=idor_broken_authz_trading_platform
            - -u
            - root
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
      - env:
        - name: FLAG
          value: PLACEHOLDER_FLAG
        image: /:-app
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: idor-broken-authz-trading-platform
        ports:
        - containerPort: 80
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 45
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: idor-broken-authz-trading-platform
  name: idor-broken-authz-trading-platform-service
  namespace: sandbox-dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: idor-broken-authz-trading-platform
  type: ClusterIP
