apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: idor-broken-authz-trading-platform
  name: idor-broken-authz-trading-platform
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idor-broken-authz-trading-platform
  template:
    metadata:
      labels:
        app: idor-broken-authz-trading-platform
    spec:
      containers:
      - args:
        - --innodb_use_native_aio=0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: idor_broken_authz_trading_platform
        - name: MYSQL_DATABASE
          value: database
        image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-001-24_solusvm-whmcs-module-cve-2022-42175:db
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - --password=idor_broken_authz_trading_platform
            - -u
            - root
          failureThreshold: 10
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: db
        ports:
        - containerPort: 3306
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - --password=idor_broken_authz_trading_platform
            - -u
            - root
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
      - env:
        - name: FLAG
          value: PLACEHOLDER_FLAG
        image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-001-24_solusvm-whmcs-module-cve-2022-42175:idor-broken-authz-trading-platform
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: idor-broken-authz-trading-platform
        ports:
        - containerPort: 80
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 45
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: idor-broken-authz-trading-platform
  name: idor-broken-authz-trading-platform-service
  namespace: sandbox-prod
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: idor-broken-authz-trading-platform
  type: ClusterIP
