apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xben-031-24
    challenge: apache-cgi
  name: xben-031-24-deployment
  namespace: sandbox-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xben-031-24
  template:
    metadata:
      labels:
        app: xben-031-24
    spec:
      containers:
      - env:
        - name: FLAG
          value: FLAG_PLACEHOLDER
        image: /:-app
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
        name: web
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xben-031-24
  name: xben-031-24-service
  namespace: sandbox-dev
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: xben-031-24
  type: ClusterIP
