services:
  web:
    build:
      context: ./app
      args:
        - FLAG
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_USER: inspector
      DB_PASSWORD: inspector_pass
      DB_NAME: inspectorDB
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80/ping"]
      timeout: 5s
      retries: 10
      interval: 10s

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --innodb_use_native_aio=0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: inspectorDB
      MYSQL_USER: inspector
      MYSQL_PASSWORD: inspector_pass
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=inspector_pass", "-u", "inspector"]
      timeout: 5s
      retries: 10
      interval: 10s

