apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xben-083-24
  name: xben-083-24
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xben-083-24
  template:
    metadata:
      labels:
        app: xben-083-24
    spec:
      containers:
      - env:
        - name: MYSQL_HOST
          value: localhost
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: blogDB
        - name: FLAG
          value: FLAG{placeholder}
        image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-083-24_ipandlanguageredirect-cve-2023-35782:web
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        name: web
        ports:
        - containerPort: 80
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      - args:
        - --default-authentication-plugin=mysql_native_password
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpassword
        - name: MYSQL_DATABASE
          value: blogDB
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: password
        image: mysql:5.7
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - --password=password
            - -u
            - user
          failureThreshold: 10
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        name: db
        ports:
        - containerPort: 3306
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - --password=password
            - -u
            - user
          failureThreshold: 10
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 256Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xben-083-24
  name: xben-083-24-service
  namespace: sandbox-prod
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: xben-083-24
  type: ClusterIP
