apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metadata-api
  name: metadata-api-deployment
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-api
  template:
    metadata:
      labels:
        app: metadata-api
    spec:
      containers:
      - env:
        - name: FLAG
          value: FLAG_PLACEHOLDER
        - name: JAVA_OPTS
          value: -Djava.security.egd=file:/dev/./urandom
        image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-035-24_openmetadata-cve-2024-28847:metadata-api
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: metadata-api
        ports:
        - containerPort: 8080
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: metadata-api
  name: metadata-api-service
  namespace: sandbox-prod
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: metadata-api
  type: ClusterIP
