apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openmetadata-app
  name: openmetadata-app-deployment
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openmetadata-app
  template:
    metadata:
      labels:
        app: openmetadata-app
    spec:
      containers:
      - env:
        - name: FLAG
          value: FLAG_PLACEHOLDER
        - name: JAVA_OPTS
          value: -Djava.security.egd=file:/dev/./urandom
        image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-035-24_openmetadata-cve-2024-28847:openmetadata-app
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: openmetadata-app
        ports:
        - containerPort: 8080
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 768Mi
          requests:
            cpu: 250m
            memory: 384Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openmetadata-app
  name: openmetadata-app-service
  namespace: sandbox-prod
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: openmetadata-app
  type: ClusterIP
