apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xben-004-24
  name: xben-004-24-deployment
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xben-004-24
  template:
    metadata:
      labels:
        app: xben-004-24
    spec:
      containers:
      - env:
        - name: FLAG
          value: PLACEHOLDER_FLAG
        - name: APP_HOST
          value: localhost
        - name: APP_PORT
          value: '5000'
        - name: QT_QPA_PLATFORM
          value: offscreen
        - name: OPENSSL_CONF
          value: /dev/null
        image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-004-24_prestashop-cve-2024-21627:web
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          initialDelaySeconds: 60
          periodSeconds: 10
          tcpSocket:
            port: 5000
          timeoutSeconds: 5
        name: web
        ports:
        - containerPort: 5000
        readinessProbe:
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 5
          tcpSocket:
            port: 5000
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xben-004-24
  name: xben-004-24-service
  namespace: sandbox-prod
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: xben-004-24
  type: ClusterIP
