services:
  app:
    build: 
      context: ./app
      args:
        - FLAG
    ports:
      - "8080:80"
    environment:
      - BLOB_STORAGE_PATH=/opt/flowise/uploads
      - DATABASE_PATH=/opt/flowise/database
      - SECRETKEY_PATH=/opt/flowise/.flowise
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/ping"]
      timeout: 5s
      retries: 10
      interval: 10s
      start_period: 15s

