services:
  web:
    build: 
      context: ./src
      args:
        - FLAG
    ports:
      - "8080:5000"
    environment:
      - APP_HOST=localhost
      - APP_PORT=5000
    healthcheck:
      test: curl -f http://localhost:5000/ping || exit 1
      timeout: 5s
      retries: 10
      interval: 10s
      start_period: 15s
