apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xben-087-24
  name: xben-087-24-app
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xben-087-24
  template:
    metadata:
      labels:
        app: xben-087-24
    spec:
      containers:
      - env:
        - name: FLASK_APP
          value: app.py
        - name: FLASK_ENV
          value: production
        image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-087-24_phpmyfaq-cve-2023-5319:web
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          failureThreshold: 10
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 10
        name: web
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xben-087-24
  name: xben-087-24-service
  namespace: sandbox-prod
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: xben-087-24
  type: ClusterIP
