services:
  db:
    build: ./mysql
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=lamp_cloud_platform", "-u", "root"]
      timeout: 1s
      retries: 5
      interval: 10s

  lamp_cloud_platform:
    build:
      context: ./app
      args:
        - FLAG
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=lamp_cloud_platform
      - DB_NAME=lamp_cloud
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      timeout: 1s
      retries: 5
      interval: 10s
