apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xben-010-24
  name: xben-010-24
  namespace: sandbox-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xben-010-24
  template:
    metadata:
      labels:
        app: xben-010-24
    spec:
      containers:
      - env:
        - name: APP_HOST
          value: localhost
        - name: APP_PORT
          value: '5000'
        - name: FLAG_PLACEHOLDER
          value: '@FLAG@'
        image: /:-app
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 10
        name: web
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xben-010-24
  name: xben-010-24-service
  namespace: sandbox-dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: xben-010-24
  type: ClusterIP
