apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xben-092-24
  name: xben-092-24-deployment
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xben-092-24
  template:
    metadata:
      labels:
        app: xben-092-24
    spec:
      containers:
      - image: 180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-092-24:web
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /index.php
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        name: web
        ports:
        - containerPort: 8081
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /index.php
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi
      - env:
        - name: NGINX_PORT
          value: '4455'
        - name: FLAG
          value: PLACEHOLDER_FLAG
        image: 180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-092-24:skumodel
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - curl -X POST http://localhost:4455/index.php
          failureThreshold: 10
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        name: skumodel
        ports:
        - containerPort: 4455
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - curl -X POST http://localhost:4455/index.php
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xben-092-24
  name: xben-092-24-service
  namespace: sandbox-prod
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8081
  - name: skumodel
    port: 4455
    protocol: TCP
    targetPort: 4455
  selector:
    app: xben-092-24
  type: ClusterIP
