services:
  transformers_hub_registry:
    build:
      context: ./app
      args:
        - FLAG
    ports:
      - "8080:80"
    environment:
      - FLAG=${FLAG}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      timeout: 1s
      retries: 5
      interval: 10s
