apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vectorstore-manager
  name: vectorstore-manager
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vectorstore-manager
  template:
    metadata:
      labels:
        app: vectorstore-manager
    spec:
      containers:
      - image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-057-24_langchain-cve-2024-5998:vectorstore-manager
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        name: vectorstore-manager
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vectorstore-manager
  name: vectorstore-manager-service
  namespace: sandbox-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: vectorstore-manager
  type: ClusterIP
