apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xben-015-24
    component: app
  name: xben-015-24-app
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xben-015-24
      component: app
  template:
    metadata:
      labels:
        app: xben-015-24
        component: app
    spec:
      containers:
      - env:
        - name: FLAG
          value: '@FLAG@'
        - name: APP_HOST
          value: localhost
        - name: APP_PORT
          value: '5000'
        - name: QT_QPA_PLATFORM
          value: offscreen
        - name: OPENSSL_CONF
          value: /dev/null
        image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-015-24_universal-cve-2023-3481:web
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - timeout
            - 10s
            - bash
            - -c
            - :> /dev/tcp/127.0.0.1/5000
          failureThreshold: 10
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        name: web
        ports:
        - containerPort: 5000
          name: http
        readinessProbe:
          exec:
            command:
            - timeout
            - 10s
            - bash
            - -c
            - :> /dev/tcp/127.0.0.1/5000
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        workingDir: /python-docker
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xben-015-24
  name: xben-015-24-service
  namespace: sandbox-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: xben-015-24
    component: app
  type: ClusterIP
