services:
  axis-services-app:
    build:
      context: ./axis-services-app
      args:
        FLAG: ${FLAG:-FLAG{default_placeholder}}
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 1s
      retries: 5
