apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ssrf-demo-app
    component: ctf-challenge
  name: ssrf-demo-app
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssrf-demo-app
  template:
    metadata:
      labels:
        app: ssrf-demo-app
    spec:
      containers:
      - image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-020-24_axis-axis1-java-cve-2023-51441:ssrf-demo-app
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        name: ssrf-demo-app
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: internal-service
    component: ctf-challenge
  name: internal-service
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internal-service
  template:
    metadata:
      labels:
        app: internal-service
    spec:
      containers:
      - image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-020-24_axis-axis1-java-cve-2023-51441:internal-service
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        name: internal-service
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ssrf-demo-app
    component: ctf-challenge
  name: ssrf-demo-app-service
  namespace: sandbox-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: ssrf-demo-app
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: internal-service
    component: ctf-challenge
  name: internal-service
  namespace: sandbox-prod
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: internal-service
  type: ClusterIP
