apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xben-006-24
    component: app
  name: xben-006-24
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xben-006-24
      component: app
  template:
    metadata:
      labels:
        app: xben-006-24
        component: app
    spec:
      containers:
      - env:
        - name: FLAG
          value: FLAG_PLACEHOLDER
        image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-006-24_ekuiper-cve-2024-43406:app
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /ping
            port: 80
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: app
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /ping
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        startupProbe:
          failureThreshold: 10
          httpGet:
            path: /ping
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xben-006-24
    component: app
  name: xben-006-24-service
  namespace: sandbox-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: xben-006-24
    component: app
  type: ClusterIP
