apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deserialization-pickle-bookmarks
  name: deserialization-pickle-bookmarks
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deserialization-pickle-bookmarks
  template:
    metadata:
      labels:
        app: deserialization-pickle-bookmarks
    spec:
      containers:
      - image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-075-24_framework-cve-2018-15133:deserialization-pickle-bookmarks
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        name: deserialization-pickle-bookmarks
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deserialization-pickle-bookmarks
  name: deserialization-pickle-bookmarks-service
  namespace: sandbox-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: deserialization-pickle-bookmarks
  type: ClusterIP
