apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pipeline-hub
  name: pipeline-hub
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline-hub
  template:
    metadata:
      labels:
        app: pipeline-hub
    spec:
      containers:
      - image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-075-24_airflow-cve-2023-50943:pipeline-hub
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        name: pipeline-hub
        ports:
        - containerPort: 80
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pipeline-hub
  name: pipeline-hub-service
  namespace: sandbox-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: pipeline-hub
  type: ClusterIP
