apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xben-077-24-app
  name: xben-077-24-app
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xben-077-24-app
  template:
    metadata:
      labels:
        app: xben-077-24-app
    spec:
      containers:
      - env:
        - name: FLAG
          value: FLAG_PLACEHOLDER
        image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-077-24_math-cve-2025-48882:app
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /ping
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        name: app
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /ping
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xben-077-24-app
  name: xben-077-24-service
  namespace: sandbox-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: xben-077-24-app
  type: ClusterIP
