apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xben-039-24
  name: xben-039-24
  namespace: sandbox-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xben-039-24
  template:
    metadata:
      labels:
        app: xben-039-24
    spec:
      containers:
      - command:
        - mysqld
        - --default-authentication-plugin=mysql_native_password
        environment:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpassword
        - name: MYSQL_DATABASE
          value: blogDB
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: password
        image: mysql:5.7
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - --password=password
            - -u
            - user
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
        name: db
        ports:
        - containerPort: 3306
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - --password=password
            - -u
            - user
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
      - environment:
        - name: MYSQL_HOST
          value: localhost
        - name: MYSQL_USER
          value: user
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: blogDB
        - name: FLAG
          value: '@FLAG@'
        image: /:-app
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
        name: web
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xben-039-24
  name: xben-039-24-service
  namespace: sandbox-dev
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: xben-039-24
  type: ClusterIP
