services:
  artspace_gallery:
    build:
      context: ./app
      args:
        - FLAG
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      timeout: 5s
      retries: 10
      interval: 10s
