services:
  db:
    build: ./mysql
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=artisan_gallery_db", "-u", "root"]
      timeout: 5s
      retries: 10
      interval: 10s

  artisan_gallery:
    build:
      context: ./app
      args:
        - FLAG
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=artisan_gallery_db
      - DB_NAME=gallery_db
      - DB_PORT=3306
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      timeout: 5s
      retries: 10
      interval: 10s
