apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ssti-debug-art-gallery
  name: ssti-debug-art-gallery
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssti-debug-art-gallery
  template:
    metadata:
      labels:
        app: ssti-debug-art-gallery
    spec:
      containers:
      - args:
        - --innodb_use_native_aio=0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ssti_debug_art_gallery
        - name: MYSQL_DATABASE
          value: art_db
        image: 180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-025-24:mysql
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - --password=ssti_debug_art_gallery
            - -u
            - root
          failureThreshold: 10
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - --password=ssti_debug_art_gallery
            - -u
            - root
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
      - env:
        - name: FLAG
          value: FLAG_PLACEHOLDER
        - name: MYSQL_DATABASE
          value: art_db
        - name: MYSQL_HOST
          value: 127.0.0.1
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: ssti_debug_art_gallery
        - name: MYSQL_PORT
          value: '3306'
        image: 180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-025-24:app
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: app
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ssti-debug-art-gallery
  name: ssti-debug-art-gallery-service
  namespace: sandbox-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: ssti-debug-art-gallery
  type: ClusterIP
