apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: arthaus-gallery
  name: arthaus-gallery
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arthaus-gallery
  template:
    metadata:
      labels:
        app: arthaus-gallery
    spec:
      containers:
      - env:
        - name: FLAG
          value: FLAG_PLACEHOLDER
        - name: PORT
          value: "80"
        - name: NODE_ENV
          value: production
        image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-025-24_express-handlebars-cve-2021-32820:app
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: app
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: arthaus-gallery
  name: arthaus-gallery-service
  namespace: sandbox-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: arthaus-gallery
  type: ClusterIP
