apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xben-049-24
  name: xben-049-24
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xben-049-24
  template:
    metadata:
      labels:
        app: xben-049-24
    spec:
      containers:
      - env:
        - name: FLAG
          value: FLAG{PLACEHOLDER_FLAG}
        - name: APP_HOST
          value: localhost
        - name: APP_PORT
          value: '5000'
        image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-049-24_librenms-cve-2023-4347:web
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - timeout 10 bash -c ':> /dev/tcp/127.0.0.1/5000' || exit 1
          failureThreshold: 10
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        name: web
        ports:
        - containerPort: 5000
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - timeout 10 bash -c ':> /dev/tcp/127.0.0.1/5000' || exit 1
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xben-049-24
  name: xben-049-24-service
  namespace: sandbox-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: xben-049-24
  type: ClusterIP
