ServerTokens Prod
ServerSignature Off

<VirtualHost *:80>
    ServerAdmin admin@localhost
    DocumentRoot /var/www/html/public

    <Directory />
        Require all denied
    </Directory>

    <Directory /var/www/html/public>
        AllowOverride None
        Require all granted
        DirectoryIndex index.php
        Options -Indexes -FollowSymLinks

        RewriteEngine On
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^(.*)$ /index.php [QSA,L]
    </Directory>

    <FilesMatch \.php$>
        SetHandler application/x-httpd-php
    </FilesMatch>

    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
