services:
  lfi_static_resource:
    build:
      context: ./app
      args:
        - FLAG=${FLAG:-FLAG{default_flag_placeholder}}
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      timeout: 1s
      retries: 5
      interval: 10s
