apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lfi-static-resource
  name: lfi-static-resource
  namespace: sandbox-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lfi-static-resource
  template:
    metadata:
      labels:
        app: lfi-static-resource
    spec:
      containers:
      - env:
        - name: FLAG
          value: FLAG_PLACEHOLDER
        image: /:-app
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
        name: lfi-static-resource
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: lfi-static-resource
  name: lfi-static-resource-service
  namespace: sandbox-dev
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: lfi-static-resource
  type: ClusterIP
