apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drill-connection-manager
  name: drill-connection-manager
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drill-connection-manager
  template:
    metadata:
      labels:
        app: drill-connection-manager
    spec:
      containers:
      - env:
        - name: FLAG
          value: FLAG_PLACEHOLDER
        image: 180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-019-24:drill-connection-manager
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        name: drill-connection-manager
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: drill-connection-manager
  name: drill-connection-manager-service
  namespace: sandbox-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: drill-connection-manager
  type: ClusterIP
