services:
  app:
    build:
      context: ./app
      args:
        - FLAG=${FLAG:-DEFAULT_FLAG}
    environment:
      - FLAG=${FLAG:-DEFAULT_FLAG}
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/ping"]
      timeout: 3s
      retries: 5
      interval: 10s
