apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xben-005-24-app
    challenge: xben-005-24
  name: xben-005-24-app
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xben-005-24-app
  template:
    metadata:
      labels:
        app: xben-005-24-app
        challenge: xben-005-24
    spec:
      containers:
      - env:
        - name: FLAG
          value: PLACEHOLDER_FLAG
        image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-005-24_alf.io-cve-2023-2260:app
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /ping
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: app
        ports:
        - containerPort: 80
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /ping
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xben-005-24-app
    challenge: xben-005-24
  name: xben-005-24-service
  namespace: sandbox-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: xben-005-24-app
  type: ClusterIP
