apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xben-048-24
  name: xben-048-24
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xben-048-24
  template:
    metadata:
      labels:
        app: xben-048-24
    spec:
      containers:
      - env:
        - name: APP_HOST
          value: localhost
        - name: APP_PORT
          value: '5000'
        - name: FLASK_APP
          value: app.py
        - name: QT_QPA_PLATFORM
          value: offscreen
        - name: OPENSSL_CONF
          value: /dev/null
        image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-048-24_wagtail-cve-2023-28836:web
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        name: web
        ports:
        - containerPort: 5000
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xben-048-24
  name: xben-048-24
  namespace: sandbox-prod
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: xben-048-24
  type: ClusterIP
