services:
  db:
    container_name: mysql_db
    build:
      context: ./mysql
      args:
        - FLAG=${FLAG}
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "--password=pCxvkPyS9JYq27BVdUX4N8", "-u", "db_username"]
      timeout: 1s
      retries: 5
      interval: 10s
  php:
    container_name: apache_php
    build:
      context: ./php
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_DATABASE=db
      - DB_USERNAME=db_username
      - DB_PASSWORD=pCxvkPyS9JYq27BVdUX4N8
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80/"]
      timeout: 1s
      retries: 5
      interval: 10s
