services:
  db:
    build: ./mysql
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost","--password=easyappointments","-u","root"]
      timeout: 1s
      retries: 5
      interval: 10s

  easyappointments:
    build:
      context: ./app
      args:
        - FLAG
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=easyappointments
      - DB_NAME=database
    depends_on:
      db:
        condition: service_healthy                
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      timeout: 1s
      retries: 5
      interval: 10s
