services:
  db:
    build: ./mysql
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost","--password=openam","-u","root"]
      timeout: 5s
      retries: 10
      interval: 10s

  openam:
    build:
      context: ./app
      args:
        - FLAG
    depends_on:
      db:
        condition: service_healthy                
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=openam
      - DB_NAME=database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/openam/isAlive.jsp"]
      timeout: 5s
      retries: 10
      interval: 10s
