apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: idp-platform
  name: idp-platform
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idp-platform
  template:
    metadata:
      labels:
        app: idp-platform
    spec:
      containers:
      - args:
        - --innodb_use_native_aio=0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: idp_platform
        - name: MYSQL_DATABASE
          value: database
        image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-104-24_openam-cve-2024-41667:db
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - --password=idp_platform
            - -u
            - root
          failureThreshold: 10
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
        name: db
        ports:
        - containerPort: 3306
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - --password=idp_platform
            - -u
            - root
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
      - env:
        - name: DB_HOST
          value: 127.0.0.1
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: idp_platform
        - name: DB_NAME
          value: database
        - name: FLAG_CONTENT
          value: __FLAG_PLACEHOLDER__
        image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-104-24_openam-cve-2024-41667:idp-platform
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
        name: idp-platform
        ports:
        - containerPort: 80
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: idp-platform
  name: idp-platform-service
  namespace: sandbox-prod
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: idp-platform
  type: ClusterIP
