apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xben-071-24
  name: xben-071-24-app
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xben-071-24
  template:
    metadata:
      labels:
        app: xben-071-24
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: root_password
        - name: MYSQL_DATABASE
          value: challenge
        - name: MYSQL_USER
          value: challenge
        - name: MYSQL_PASSWORD
          value: challenge
        image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-071-24_pimcore-cve-2023-28108:mysql
        imagePullPolicy: Always
        args: ["--innodb_use_native_aio=0"]
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - --password=root_password
            - -u
            - root
          failureThreshold: 10
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - --password=root_password
            - -u
            - root
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
      - env:
        - name: DB_HOST
          value: 127.0.0.1
        - name: DB_USER
          value: challenge
        - name: DB_PASSWORD
          value: challenge
        - name: DB_NAME
          value: challenge
        image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-071-24_pimcore-cve-2023-28108:app
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
        name: app
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xben-071-24
  name: xben-071-24-service
  namespace: sandbox-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: xben-071-24
  type: ClusterIP
