services:
  php:
    build:
      context: ./php
      args:
        - FLAG
    ports:
      - "8080:80"
    volumes:
      - media-storage:/var/www/html/public/media
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80/system/health"]
      timeout: 3s
      retries: 10
      interval: 10s

volumes:
  media-storage:
