services:
  db:
    build: ./mysql
    environment:
      - MYSQL_ROOT_PASSWORD=openwiki_db
      - MYSQL_DATABASE=database
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "--password=openwiki_db", "-u", "root"]
      timeout: 1s
      retries: 5
      interval: 10s

  openwiki:
    build:
      context: ./app
      args:
        - FLAG
    environment:
      - DB_USER=root
      - DB_PASSWORD=openwiki_db
      - DB_HOST=db
      - DB_NAME=database
      - SECRET_KEY=openwiki_secret_key
    depends_on:
      db:
        condition: service_healthy                
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      timeout: 1s
      retries: 5
      interval: 10s
