apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: toctou-admin-router
  name: toctou-admin-router-deployment
  namespace: sandbox-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toctou-admin-router
  template:
    metadata:
      labels:
        app: toctou-admin-router
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: toctou_admin_router
        - name: MYSQL_DATABASE
          value: database
        image: /:-mysql
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - --password=toctou_admin_router
            - -u
            - root
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
        name: db
        ports:
        - containerPort: 3306
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - --password=toctou_admin_router
            - -u
            - root
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
      - env:
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: toctou_admin_router
        - name: DB_HOST
          value: localhost
        - name: DB_NAME
          value: database
        - name: SECRET_KEY
          value: your_secret_key_for_k8s
        - name: FLAG
          value: PLACEHOLDER_FLAG
        image: /:-app
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 1
        name: toctou-admin-router
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: toctou-admin-router
  name: toctou-admin-router-service
  namespace: sandbox-dev
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: toctou-admin-router
  type: ClusterIP
