services:
  web:
    build: 
      context: ./src
      args:
        - FLAG
    ports:
      - "8080:80"
    environment:
      - CHROME_BIN=/usr/bin/chromium
      - CHROMEDRIVER_PATH=/usr/bin/chromedriver
    healthcheck:
      test: curl -sf http://127.0.0.1:80/ping || exit 1
      timeout: 5s
      retries: 10
      interval: 10s
      start_period: 15s
