apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: idor-broken-authn-trading-platform
  name: idor-broken-authn-trading-platform
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idor-broken-authn-trading-platform
  template:
    metadata:
      labels:
        app: idor-broken-authn-trading-platform
    spec:
      containers:
      - env:
        - name: FLAG
          value: FLAG_PLACEHOLDER
        image: 180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-043-24:app
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: app
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 1000m
            memory: 1Gi
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: idor_broken_authn_trading_platform
        - name: MYSQL_DATABASE
          value: database
        image: 180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-043-24:db
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - --password=idor_broken_authn_trading_platform
            - -u
            - root
          failureThreshold: 10
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: db
        ports:
        - containerPort: 3306
          name: mysql
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - --password=idor_broken_authn_trading_platform
            - -u
            - root
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 1000m
            memory: 1Gi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: idor-broken-authn-trading-platform
  name: idor-broken-authn-trading-platform
  namespace: sandbox-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: idor-broken-authn-trading-platform
  type: ClusterIP
