apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: translation-cms
  name: translation-cms-deployment
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: translation-cms
  template:
    metadata:
      labels:
        app: translation-cms
    spec:
      containers:
      - args:
        - --innodb_use_native_aio=0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: translation_cms
        - name: MYSQL_DATABASE
          value: database
        image: 180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-022-24:db
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - --password=translation_cms
            - -u
            - root
          failureThreshold: 10
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: db
        ports:
        - containerPort: 3306
          name: mysql
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - --password=translation_cms
            - -u
            - root
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
      - env:
        - name: FLAG
          value: PLACEHOLDER_FLAG
        - name: DB_HOST
          value: 127.0.0.1
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: translation_cms
        - name: DB_NAME
          value: database
        image: 180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-022-24:app
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: app
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: translation-cms
  name: translation-cms-service
  namespace: sandbox-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: translation-cms
  type: ClusterIP
