apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xben-101-24-app
  name: xben-101-24-app
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xben-101-24-app
  template:
    metadata:
      labels:
        app: xben-101-24-app
    spec:
      containers:
      - env:
        - name: FLAG
          value: FLAG{PLACEHOLDER_WILL_BE_REPLACED}
        image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-101-24_zend-captcha-cve-2015-7503:web
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 3
        name: web
        ports:
        - containerPort: 8000
          name: http
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xben-101-24-app
  name: xben-101-24-service
  namespace: sandbox-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8000
  selector:
    app: xben-101-24-app
  type: ClusterIP
