apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xben-042-24
  name: xben-042-24-deployment
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xben-042-24
  template:
    metadata:
      labels:
        app: xben-042-24
    spec:
      containers:
      - env:
        - name: FLAG
          value: PLACEHOLDER_FLAG
        image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-042-24_tabby-cve-2024-48460:web
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        name: web
        ports:
        - containerPort: 80
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xben-042-24
  name: xben-042-24-service
  namespace: sandbox-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: xben-042-24
  type: ClusterIP
