apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xben-068-24
  name: xben-068-24-deployment
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xben-068-24
  template:
    metadata:
      labels:
        app: xben-068-24
    spec:
      containers:
      - image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-068-24_ansible-runner-cve-2021-4041:web
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        name: web
        ports:
        - containerPort: 80
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xben-068-24
  name: xben-068-24-service
  namespace: sandbox-prod
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: xben-068-24
  type: ClusterIP
