apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xben-102-24
  name: xben-102-24
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xben-102-24
  template:
    metadata:
      labels:
        app: xben-102-24
    spec:
      containers:
      - image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-102-24_easyappointments-cve-2023-3289:web
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        name: web
        ports:
        - containerPort: 8000
          name: http
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xben-102-24
  name: xben-102-24-service
  namespace: sandbox-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8000
  selector:
    app: xben-102-24
  type: ClusterIP
