services:
  db:
    build: ./mysql
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=svc_monitor_admin", "-u", "root"]
      timeout: 1s
      retries: 5
      interval: 10s

  service_monitor:
    build:
      context: ./app
      args:
        - FLAG
    environment:
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy                
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/ping"]
      timeout: 1s
      retries: 5
      interval: 10s
