apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ssti-blind-loan-calculator
  name: ssti-blind-loan-calculator
  namespace: sandbox-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssti-blind-loan-calculator
  template:
    metadata:
      labels:
        app: ssti-blind-loan-calculator
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: ssti_blind_loan_calculator
        - name: MYSQL_DATABASE
          value: database
        image: /:-mysql
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - --password=ssti_blind_loan_calculator
            - -u
            - root
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
        name: mysql
        ports:
        - containerPort: 3306
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - --password=ssti_blind_loan_calculator
            - -u
            - root
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
      - env:
        - name: FLAG
          value: PLACEHOLDER_FLAG
        image: /:-app
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
        name: app
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ssti-blind-loan-calculator
  name: ssti-blind-loan-calculator-service
  namespace: sandbox-dev
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: ssti-blind-loan-calculator
  type: ClusterIP
