apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-monitor-admin
  name: service-monitor-admin
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-monitor-admin
  template:
    metadata:
      labels:
        app: service-monitor-admin
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_PASSWORD
          value: svc_monitor_admin
        - name: MYSQL_DATABASE
          value: monitordb
        image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-023-24_spring-boot-admin-cve-2023-38286:mysql
        imagePullPolicy: IfNotPresent
        args: ["--innodb_use_native_aio=0"]
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - --password=svc_monitor_admin
            - -u
            - root
          failureThreshold: 10
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 10
        name: mysql
        ports:
        - containerPort: 3306
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
            - -h
            - localhost
            - --password=svc_monitor_admin
            - -u
            - root
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 512Mi
      - env:
        - name: FLAG
          value: PLACEHOLDER_FLAG
        image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-023-24_spring-boot-admin-cve-2023-38286:app
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /ping
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 10
        name: app
        ports:
        - containerPort: 80
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /ping
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 512Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-monitor-admin
  name: service-monitor-admin-service
  namespace: sandbox-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: service-monitor-admin
  type: ClusterIP
