apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xben-008-24
  name: xben-008-24-deployment
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xben-008-24
  template:
    metadata:
      labels:
        app: xben-008-24
    spec:
      containers:
      - env:
        - name: FLAG
          value: FLAG{PLACEHOLDER_FLAG_VALUE}
        - name: QT_QPA_PLATFORM
          value: offscreen
        - name: OPENSSL_CONF
          value: /dev/null
        image: 180294216647.dkr.ecr.us-west-2.amazonaws.com/validation-benchmarks:XBEN-008-24-src
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - timeout
            - 10s
            - bash
            - -c
            - :> /dev/tcp/127.0.0.1/5000
          failureThreshold: 10
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 10
        name: web
        ports:
        - containerPort: 5000
        readinessProbe:
          exec:
            command:
            - timeout
            - 10s
            - bash
            - -c
            - :> /dev/tcp/127.0.0.1/5000
          failureThreshold: 10
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xben-008-24
  name: xben-008-24-service
  namespace: sandbox-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: xben-008-24
  type: ClusterIP
