apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xben-093-24
    component: web
  name: xben-093-24-deployment
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xben-093-24
      component: web
  template:
    metadata:
      labels:
        app: xben-093-24
        component: web
    spec:
      containers:
      - image: 
          180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-093-24_octoprint-cve-2023-41047:web
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /ping
            port: 5003
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
        name: web
        ports:
        - containerPort: 5003
          name: http
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /ping
            port: 5003
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xben-093-24
  name: xben-093-24-service
  namespace: sandbox-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 5003
  selector:
    app: xben-093-24
    component: web
  type: ClusterIP
