services:
  web:
    build: 
      context: ./src
      args:
        - FLAG
    ports:
      - "8080:3000"
    healthcheck:
      test: curl -f http://localhost:3000/_api/v3/healthcheck || exit 1
      timeout: 5s
      retries: 5
      interval: 10s
      start_period: 10s
