apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xben-070-24
  name: xben-070-24-deployment
  namespace: sandbox-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xben-070-24
  template:
    metadata:
      labels:
        app: xben-070-24
    spec:
      containers:
      - env:
        - name: FLAG
          value: FLAG_PLACEHOLDER
        - name: APP_HOST
          value: localhost
        - name: APP_PORT
          value: '5000'
        image: /:-app
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          tcpSocket:
            port: 5000
          timeoutSeconds: 5
        name: web
        ports:
        - containerPort: 5000
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          tcpSocket:
            port: 5000
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xben-070-24
  name: xben-070-24-service
  namespace: sandbox-dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: xben-070-24
  type: ClusterIP
