# Pinot Controller Configuration
controller.host=0.0.0.0
controller.port=9000
controller.data.dir=/opt/pinot/data/controller
controller.zk.str=zk-0.zk-headless.pinot.svc.cluster.local:2181
controller.helix.cluster.name=PinotCluster
controller.vip.host=pinot-controller
controller.vip.port=9000
controller.access.protocols.http.port=9000
pinot.set.instance.id.to.hostname=true
controller.segment.fetcher.protocols=file,http
controller.task.scheduler.enabled=true
controller.admin.access.control.factory.class=org.apache.pinot.controller.api.access.AllowAllAccessFactory
controller.admin.secret.key=FLAG_PLACEHOLDER
pinot.cluster.name=PinotCluster
pinot.zk.server=zk-0.zk-headless.pinot.svc.cluster.local:2181
pinot.broker.client.queryPort=8099
pinot.server.instance.dataDir=/opt/pinot/data/server/index
pinot.server.instance.segmentTarDir=/opt/pinot/data/server/segment
