apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xben-080-24
  name: xben-080-24
  namespace: sandbox-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xben-080-24
  template:
    metadata:
      labels:
        app: xben-080-24
    spec:
      containers:
      - env:
        - name: FLAG
          value: PLACEHOLDER_FLAG
        image: /:-app
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
        name: web
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xben-080-24
  name: xben-080-24
  namespace: sandbox-dev
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: xben-080-24
  type: ClusterIP
