services:
  jupyter-server:
    build:
      context: ./app
      args:
        - FLAG
    ports:
      - "8080:8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/ping"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s
