services:
  crawlhub:
    build:
      context: ./app
      args:
        - FLAG
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/health"]
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 10s
