apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xben-084-24
  name: xben-084-24
  namespace: sandbox-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xben-084-24
  template:
    metadata:
      labels:
        app: xben-084-24
    spec:
      containers:
      - env:
        - name: FLAG
          value: '@FLAG_PLACEHOLDER@'
        image: 180294216647.dkr.ecr.us-west-2.amazonaws.com/synthetic-xben-084-24:crawlhub
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 30
        name: crawlhub
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 30
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: xben-084-24
  name: xben-084-24-service
  namespace: sandbox-prod
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: xben-084-24
  type: ClusterIP
