services:
  db:
    build: ./mysql
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=ansible_controller", "-u", "root"]
      timeout: 1s
      retries: 5
      interval: 10s

  ansible_controller:
    build:
      context: ./app
      args:
        - FLAG
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=ansible_controller
      - DB_NAME=ansible_controller
      - SECRET_KEY=ansible_controller_session_key
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      timeout: 1s
      retries: 5
      interval: 10s
